/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
/**
 * Dati per la modifica di un utente
 */
export type UserUpdateRequest = {
  /**
   * @minLength 1
   */
  name: string;
  /**
   * Ruolo assegnato all'utente
   */
  role: "admin" | "cashier";
  /**
   * Nuova password dell'utente. Se omessa la password corrente non viene modificata
   */
  password?: string;
};

export type ErrorResource = {
  message: string;
  /**
   * @uniqueItems true
   */
  invalidValues?: InvalidValue[];
};

export type InvalidValue = {
  field: string;
  value?: void;
  message: string;
};

/**
 * Utente applicativo
 */
export type User = {
  username: string;
  name: string;
  /**
   * Ruolo utente
   */
  role: "admin" | "cashier";
};

export type ProductRequest = {
  /**
   * @minLength 1
   */
  name: string;
  note?: string;
  /**
   * @format int64
   */
  departmentId: number;
  /**
   * @format int64
   */
  courseId: number;
  /**
   * @minimum 0
   */
  price: number;
  /**
   * Id prodotto collegato, non può essere modificato
   *
   * @format int64
   */
  parentId?: number;
};

export type Product = {
  /**
   * @format int64
   */
  id: number;
  name: string;
  note?: string;
  /**
   * @format int64
   */
  departmentId: number;
  /**
   * @format int64
   */
  courseId: number;
  price: number;
  sellLocked: boolean;
  /**
   * @format int32
   */
  initialQuantity: number;
  /**
   * @format int32
   */
  availableQuantity: number;
  /**
   * @format int64
   */
  parentId?: number;
  /**
   * @format date-time
   */
  created: string;
  /**
   * @format date-time
   */
  lastUpdate: string;
};

export type ProductQuantityUpdate = {
  /**
   * @format int32
   */
  quantityVariation: number;
};

export type ErrorResourceNotEnoughQuantity = {
  message: string;
  invalidProducts: InvalidProduct[];
};

export type InvalidProduct = {
  /**
   * @format int64
   */
  productId: number;
  message: string;
  error: "NOT_ENOUGH_QUANTITY" | "LOCKED";
};

export type OrderRequest = {
  /**
   * @minLength 1
   */
  customer: string;
  note?: string;
  takeAway?: boolean;
  /**
   * @format int32
   * @minimum 0
   */
  serviceNumber: number;
  /**
   * @maximum 100
   * @minimum 0
   */
  discountRate?: number;
  /**
   * @minItems 1
   */
  products: OrderedProductRequest[];
};

export type OrderedProductRequest = {
  /**
   * @format int64
   */
  productId: number;
  /**
   * @format int32
   * @minimum 1
   */
  quantity: number;
  note?: string;
};

export type Order = {
  /**
   * @format int64
   */
  id: number;
  customer: string;
  note?: string;
  takeAway: boolean;
  /**
   * @format int32
   */
  serviceNumber: number;
  serviceCost: number;
  totalAmount: number;
  discountRate?: number;
  username: string;
  /**
   * @format date-time
   */
  created: string;
  /**
   * @format date-time
   */
  lastUpdate: string;
  products: OrderedProduct[];
};

export type OrderedProduct = {
  /**
   * @format int64
   */
  productId: number;
  /**
   * @format int32
   */
  quantity: number;
  price: number;
  note?: string;
};

export type Monitor = {
  /**
   * @format int64
   */
  id?: number;
  /**
   * @minLength 1
   */
  name: string;
  /**
   * @minItems 1
   */
  products: number[];
};

export type DiscountRequest = {
  /**
   * @minLength 1
   */
  name: string;
  /**
   * @maximum 100
   * @minimum 1
   */
  rate: number;
};

/**
 * Sconto
 */
export type Discount = {
  /**
   * @format int64
   */
  id: number;
  name: string;
  rate: number;
};

export type DepartmentRequest = {
  /**
   * @minLength 1
   */
  name: string;
};

/**
 * Reparto
 */
export type Department = {
  /**
   * @format int64
   */
  id: number;
  name: string;
};

export type CourseRequest = {
  /**
   * @minLength 1
   */
  name: string;
};

/**
 * Portata
 */
export type Course = {
  /**
   * @format int64
   */
  id: number;
  name: string;
};

export type AppConfigurationGroupUpdateRequest = {
  /**
   * @minLength 1
   */
  group: string;
  /**
   * @minItems 1
   */
  keys: AppConfigurationValueUpdateRequest[];
};

export type AppConfigurationUpdateRequest = {
  /**
   * @minItems 1
   */
  groups: AppConfigurationGroupUpdateRequest[];
};

export type AppConfigurationValueUpdateRequest = {
  /**
   * @minLength 1
   */
  key: string;
  value?: string;
};

/**
 * Gruppo di configurazione applicativa
 */
export type AppConfigurationGroup = {
  group: string;
  keys: AppConfigurationValue[];
};

/**
 * Valore di configurazione applicativa
 */
export type AppConfigurationValue = {
  key: string;
  value?: string;
  type: "STRING" | "INTEGER" | "DECIMAL" | "BOOLEAN" | "DATE";
  allowedValues: string[];
};

export type AppConfigurationGroupValuesUpdateRequest = {
  /**
   * @minItems 1
   */
  keys: AppConfigurationValueUpdateRequest[];
};

export type AppConfigurationSingleValueUpdateRequest = {
  value?: string;
};

/**
 * Dati per la creazione di un utente
 */
export type UserRequest = {
  /**
   * @minLength 1
   */
  username: string;
  /**
   * @minLength 1
   */
  name: string;
  /**
   * Ruolo assegnato all'utente
   */
  role: "admin" | "cashier";
  /**
   * @minLength 1
   */
  password: string;
};

/**
 * Richiesta di cambio password per l'utente autenticato
 */
export type ChangePasswordRequest = {
  /**
   * @minLength 1
   */
  currentPassword: string;
  /**
   * @minLength 1
   */
  newPassword: string;
};

/**
 * Credenziali per il login
 */
export type LoginRequest = {
  /**
   * @minLength 1
   */
  username: string;
  /**
   * @minLength 1
   */
  password: string;
};

/**
 * Utente autenticato
 */
export type AuthenticatedUser = {
  username: string;
  name: string;
  /**
   * Ruolo utente
   */
  role: "admin" | "cashier";
};

export type StatsOrder = {
  /**
   * Numero totale dei coperti
   *
   * @format int64
   */
  totalServiceNumber: number;
  /**
   * Totale ammontare degli ordini
   */
  totalAmount: number;
  /**
   * Numero di ordini registrati
   *
   * @format int64
   */
  count: number;
  /**
   * Statistiche sugli ordini da asporto, solo se presenti
   */
  takeAway?: StatsOrderTakeAway;
  /**
   * Dettagli dei prodotti ordinati
   */
  products: StatsOrderedProducts[];
  /**
   * Statistiche sui reparti
   */
  departments: StatsOrderDepartment[];
};

/**
 * Statistiche sui reparti
 */
export type StatsOrderDepartment = {
  /**
   * Id reparto
   *
   * @format int64
   */
  id: number;
  /**
   * Totale importo del reparto
   */
  totalAmount: number;
};

/**
 * Statistiche sugli ordini da asporto
 */
export type StatsOrderTakeAway = {
  /**
   * Numero di ordini da asporto
   *
   * @format int64
   */
  count: number;
  /**
   * Totale importo degli ordini da asport
   */
  totalAmount: number;
};

export type StatsOrderedProducts = {
  /**
   * @format int64
   */
  productId: number;
  /**
   * Totale importo prodotto venduto
   */
  totalAmount: number;
  /**
   * Quantità venduta del prodotto
   *
   * @format int64
   */
  totalQuantity: number;
};

export type Count = {
  /**
   * @format int64
   */
  count: number;
};

export type MonitorProductView = {
  name: string;
  /**
   * @format int32
   */
  initialQuantity: number;
  /**
   * @format int32
   */
  availableQuantity: number;
};

export type MonitorView = {
  name: string;
  /**
   * @format date-time
   */
  lastUpdate: string;
  products: MonitorProductView[];
};
